# Copyright (c) 2026 The Regents of the University of California
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from pathlib import Path

from pyunit.stats.stats_txt import parse_stats_file
from testlib import *


class CheckStatsReset(verifier.Verifier):
    """Validate before/reset/after stats generated by one gem5 invocation."""

    _TOLERANCE = 1e-9
    _DUMP_MESSAGES = ("before reset", "after reset")

    _RESETTABLE_STATS = {
        "system.reset_scalar": (
            "zero",
            "ScalarStatTester sets this value before reset and does not "
            "update it again.",
        ),
        "simTicks": (
            "less_than_before",
            "simTicks reports ticks since the last stats reset.",
        ),
    }

    # These lifetime/constant stats are intentionally not compared. The test
    # checks selected resettable stats instead of diffing the whole stats file.
    _NON_RESET_STATS_ALLOWLIST = {
        "finalTick": "total tick from simulation start; intentionally not reset",
        "simFreq": "constant ticks-per-second value",
        "hostSeconds": "host wall-clock measurement",
        "hostTickRate": "derived host performance measurement",
        "hostMemory": "host process memory measurement",
    }

    def test(self, params):
        tempdir = params.fixtures[constants.tempdir_fixture_name].path
        stats_path = Path(tempdir) / constants.gem5_simulation_stats
        dumps = parse_stats_file(stats_path)

        failures = []
        if len(dumps) != 2:
            failures.append(
                f"expected exactly 2 stats dumps, found {len(dumps)}"
            )
        else:
            for dump, message in zip(dumps, self._DUMP_MESSAGES):
                if dump.message != message:
                    failures.append(
                        "expected dump at line {} to be {!r}, found {!r}".format(
                            dump.line_number,
                            message,
                            dump.message,
                        )
                    )

            before, after = dumps
            for stat_name, expectation in self._RESETTABLE_STATS.items():
                self._check_stat(
                    stat_name, expectation, before, after, failures
                )

        if failures:
            raise AssertionError(
                "m5.stats.reset() validation failed for {}:\n{}".format(
                    stats_path,
                    "\n".join("  - " + failure for failure in failures),
                )
            )

    def _check_stat(self, stat_name, expectation, before, after, failures):
        check, reason = expectation
        if stat_name not in before.stats:
            failures.append(
                "{}: missing from before-reset dump; {}".format(
                    stat_name,
                    reason,
                )
            )
            return

        before_value = before.stats[stat_name]
        after_missing = stat_name not in after.stats
        after_value = 0.0 if after_missing else after.stats[stat_name]
        after_text = (
            "absent (treated as 0 because zero-valued stats may be omitted)"
            if after_missing
            else repr(after_value)
        )

        if check == "zero":
            if abs(after_value) > self._TOLERANCE:
                failures.append(
                    "{}: before={!r}, after={}; expected reset value to be "
                    "zero; {}".format(
                        stat_name,
                        before_value,
                        after_text,
                        reason,
                    )
                )
        elif check == "less_than_before":
            if before_value <= self._TOLERANCE:
                failures.append(
                    "{}: before={!r}; expected positive before-reset value; "
                    "{}".format(stat_name, before_value, reason)
                )
            elif after_value + self._TOLERANCE >= before_value:
                failures.append(
                    "{}: before={!r}, after={}; expected after-reset value "
                    "to be lower than before-reset value; {}".format(
                        stat_name,
                        before_value,
                        after_text,
                        reason,
                    )
                )
        else:
            raise ValueError(f"unknown reset expectation: {check}")


gem5_verify_config(
    name="stats-reset-check",
    fixtures=(),
    verifiers=(CheckStatsReset(),),
    config=joinpath(
        config.base_dir,
        "tests",
        "gem5",
        "stats",
        "configs",
        "stats_reset_check.py",
    ),
    config_args=[],
    valid_isas=(constants.null_tag,),
    length=constants.quick_tag,
)
